### PR TITLE
Create impact_of_S.py

### PR DESCRIPTION
**Pull request by jakob-the-killer**
I have created this program to test the impact of S on model performance by testing on out of sample data. I want to give a special shoutout to Jens August who provided the initial code that I have built upon.

### CODE REVIEW

**Comment by jennerstrom** [comment]
Please update the description to reflect how important I was in this process. The current description shows me to be a secondary source of power while I, in reality, am the greatest programmer to ever live. XO

**Comment by jakob-the-killer** [comment]
This is not the way I see it I see you as a mediocre copilot merchant😡 You should be happy that you are even mentioned in my credits!

**Comment by jennerstrom** [comment]
I would like to add that I have not had Copilot turned on for months, it writes poor code compared to me and was merely an obstruction. Please update the original description to reflect my contributions.

BR

**Comment by jakob-the-killer** [comment]
😡😡😡😡

**Pull request merged**
